# Generated by Django 5.1.7 on 2025-03-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('years', models.IntegerField()),
                ('student_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
    ]
