# Generated by Django 5.1.7 on 2025-03-22 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlesheetdata',
            name='birthdate',
        ),
    ]
