# Generated by Django 5.1.7 on 2025-03-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_students', '0002_remove_googlesheetdata_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesheetdata',
            name='years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
